name: 'Bruno Action'
description: 'The Action to run Bruno API Collections'
inputs:
  directory:  # id of input
    description: 'Directory where your API collection resides'
    required: true
    default: '/.'
runs:
  using: "composite"
  steps:
    - name: Bruno - install
        run: npm install -g @usebruno/cli
    - name: Bruno - Run collection
      id: bruno_run
      working-directory: ${{ inputs.directory }}
      run: bru run
          

