name: 'Bruno Action'
description: 'The Action to run Bruno API Collections'
inputs:
  directory:  # id of input
    description: 'Directory where your API collection resides'
    required: true
    default: '/.'
  environment:
    description: 'Environment file'
    required: false
  output-type:
    description: 'Whether the output is written to console or as a PR comment'
    required: false
    default: 'console'
runs:
  using: "composite"
  steps:
    - name: Bruno - install
      run: npm install -g @usebruno/cli@1.16.0
      shell: bash
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Bruno - Run collection
      id: bruno_run
      shell: bash
      run: |
        {
          cd ${{ inputs.directory }}
          echo 'bruno_output<<EOF'
          bru run
          echo EOF
        } >> "$GITHUB_ENV"

    - name: Bruno - print to console
      shell: bash
      run: echo ${{ env.bruno_output }}   
        
    - name: Bruno - create PR comment for results
      if: ${{ inputs.output-type == 'pr' }}
      uses: peter-evans/find-comment@v3
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Build output

    - name: Bruno - Create comment
      if: ${{ inputs.output-type == 'pr' }}
      uses: peter-evans/create-or-update-comment@v4
      env:
        BRUNO_OUTPUT: "Output ${{ env.bruno_output }}"
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
            ### :dog: Bruno output
            ``` ${{ env.bruno_output }} ```
          

